// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/microdemo.proto

package microdemo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Microdemo service

func NewMicrodemoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Microdemo service

type MicrodemoService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Microdemo_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Microdemo_PingPongService, error)
}

type microdemoService struct {
	c    client.Client
	name string
}

func NewMicrodemoService(name string, c client.Client) MicrodemoService {
	return &microdemoService{
		c:    c,
		name: name,
	}
}

func (c *microdemoService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Microdemo.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microdemoService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Microdemo_StreamService, error) {
	req := c.c.NewRequest(c.name, "Microdemo.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &microdemoServiceStream{stream}, nil
}

type Microdemo_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type microdemoServiceStream struct {
	stream client.Stream
}

func (x *microdemoServiceStream) Close() error {
	return x.stream.Close()
}

func (x *microdemoServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microdemoServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microdemoServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microdemoServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *microdemoService) PingPong(ctx context.Context, opts ...client.CallOption) (Microdemo_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Microdemo.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &microdemoServicePingPong{stream}, nil
}

type Microdemo_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type microdemoServicePingPong struct {
	stream client.Stream
}

func (x *microdemoServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *microdemoServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *microdemoServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microdemoServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microdemoServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *microdemoServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Microdemo service

type MicrodemoHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Microdemo_StreamStream) error
	PingPong(context.Context, Microdemo_PingPongStream) error
}

func RegisterMicrodemoHandler(s server.Server, hdlr MicrodemoHandler, opts ...server.HandlerOption) error {
	type microdemo interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Microdemo struct {
		microdemo
	}
	h := &microdemoHandler{hdlr}
	return s.Handle(s.NewHandler(&Microdemo{h}, opts...))
}

type microdemoHandler struct {
	MicrodemoHandler
}

func (h *microdemoHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MicrodemoHandler.Call(ctx, in, out)
}

func (h *microdemoHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MicrodemoHandler.Stream(ctx, m, &microdemoStreamStream{stream})
}

type Microdemo_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type microdemoStreamStream struct {
	stream server.Stream
}

func (x *microdemoStreamStream) Close() error {
	return x.stream.Close()
}

func (x *microdemoStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microdemoStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microdemoStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microdemoStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *microdemoHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MicrodemoHandler.PingPong(ctx, &microdemoPingPongStream{stream})
}

type Microdemo_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type microdemoPingPongStream struct {
	stream server.Stream
}

func (x *microdemoPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *microdemoPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microdemoPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microdemoPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microdemoPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *microdemoPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
